services:
  - type: web
    name: coffeebean-backend
    env: python
    buildCommand: ""
    startCommand: gunicorn app:app
    envVars:
      - key: SECRET_KEY
        value: coffeebean_secret
      - key: JWT_SECRET_KEY
        value: coffeebean_jwt_secret
